# General
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: detect-private-key
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.6
    hooks:
    -   id: forbid-tabs
        exclude: \.go$

# Python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.670
    hooks:
    -   id: mypy
        language_version: python3
